[package]
name = "c3_display"
version = "0.1.0"
authors = ["David Sawatzke <david-sawatzke@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32f1xx-hal = {version = "0.4.0", features = ["rt", "stm32f103"]}
panic-halt = "0.2.0"
cortex-m = "0.6.1"
embedded-hal = "0.2.3"
cortex-m-rtfm = "0.5.1"

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"
